# Generated by Django 4.2 on 2025-01-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_director_alter_movie_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(choices=[('A', 'Accion'), ('T', 'Terror'), ('R', 'Romance'), ('C', 'Comedia')], max_length=30),
        ),
    ]
